---
kind: pipeline
type: kubernetes
name: default

steps:
- name: install-and-test
  image: python:3.7
  pull: always
  commands:
    - pip install -r requirements.txt
    - pylint --disable=missing-docstring,protected-access,fixme beautifurl
    - python test.py

- name: upload
  image: python:3.7
  pull: always
  environment:
    TWINE_USERNAME:
      from_secret: pypi_username
    TWINE_PASSWORD:
      from_secret: pypi_password
  commands:
    - pip install twine wheel
    - python setup.py sdist bdist_wheel
    - twine upload --skip-existing dist/*
  when:
    branch: master
    event: push

---
kind: signature
hmac: a3eaacfb9f3399bf5d910c801b2a0e3db1619d930a211d1083a8f5a69e6c968a

...
