kind: pipeline
name: default

steps:
- name: install
  image: python
  pull: always
  volumes:
    - name: python-modules
      path: /usr/local/lib/python3.7/site-packages
  commands:
    - pip install -r requirements.txt

- name: lint
  group: verify
  image: python
  pull: always
  volumes:
    - name: python-modules
      path: /usr/local/lib/python3.7/site-packages
  commands:
    - pip install pylint
    - pylint --disable=missing-docstring,protected-access,fixme beautifurl

- name: test
  group: verify
  image: python
  pull: always
  volumes:
    - name: python-modules
      path: /usr/local/lib/python3.7/site-packages
  commands:
    - python test.py

volumes:
  - name: python-modules
    temp: {}
