kind: pipeline
name: default

steps:
- name: install
  image: python
  pull: always
  volumes:
    - name: python-modules
      path: /usr/local/lib/python3.7/site-packages
  commands:
    - pip install -r requirements.txt

- name: lint
  group: verify
  image: python
  pull: always
  volumes:
    - name: python-modules
      path: /usr/local/lib/python3.7/site-packages
  commands:
    - pip install pylint
    - pylint --disable=missing-docstring,protected-access,fixme beautifurl

- name: test
  group: verify
  image: python
  pull: always
  volumes:
    - name: python-modules
      path: /usr/local/lib/python3.7/site-packages
  commands:
    - python test.py

- name: upload
  image: python
  pull: always
  environment:
    TWINE_USERNAME:
      from_secret: pypi_username
    TWINE_PASSWORD:
      from_secret: pypi_password
  volumes:
    - name: python-modules
      path: /usr/local/lib/python3.7/site-packages
  commands:
    - pip install twine
    - python setup.py sdist bdist_wheel
    - twine upload dist/* 2>twine_error || grep "This filename has already been used, use a different version." twine_error
  when:
    branch: master
    event: push

volumes:
  - name: python-modules
    temp: {}
