name: CI

on:
  push:
  pull_request:

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.7
    - name: Install
      run: |
        pip install -r requirements.txt
    - name: Lint
      run: |
        pip install black
        black --check ./beautifurl ./test
    - name: Test
      run: |
        python test.py
    - name: Build
      run: |
        pip install wheel twine
        python setup.py sdist bdist_wheel
